# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages

image: golang:latest

before_script:
  - export GOPROXY=https://goproxy.cn
  - go get golang.org/x/tools/cmd/goimports
#  - apt-get update && apt-get install -y curl 

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - integration-test
#  - deploy

format-job:
  stage: test
  tags:
    - golang
  services:
    - name: pikadb/pika:latest
  script:
    - goimports -d .
    - test -z "$(goimports -d .)"
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -short -race $(go list ./... | grep -v /vendor/)

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - golang
  script:
    - echo "Compiling the code..."
    - cd cmd
    - go build  -race -ldflags "-extldflags '-static'" -o search_engine  main.go
    - echo "Compile complete."
    - sleep 5m
  artifacts:
    paths:
      - search_engine
      - cmd
      - configs
      - data
      - test
  
integration-test-job:
  stage: integration-test
  services:
    - name: pikadb/pika:latest
  image:
    name: node:latest
  before_script:
    - npm install -g newman
  script:
    - cd cmd
    - ./search_engine &
    - newman run ../test/searchEngine.json
#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
