[server]
ip = ""
port = 7788

[log]
level = "info"       #可能的值：debug, info, warn, error
file_path = "../logs/engine.log"
max_size = 128       #在进行切割之前，日志文件的最大大小（以MB为单位）
max_backups = 100    #保留旧文件的最大个数
max_age = 60         #保留旧文件的最大天数
compress = true      #是否压缩/归档旧文件

[analyzer]
stop_word_path = "../data/stop_word.txt"

[bloomfilter]
miscal_rate = 0.00001
add_size = 100000000
store_path = "../data/bloomfilter"

[db]
path = "../data/db/engine.db"
host = "${DBHOST||localhost}"
port = "9221"
password = ""
index = 0
timeout = 30
